export default function(){
	return[
		{title: 'javascritp:sdfasdf'},
		{title: 'java:sdfasdf'},
		{title: 'css:sdfasdf'}
	];
}
// application state is generated by reducer function ahave ultiple reduces and combi
// nnd combined unsing combinereducers from redux
// connect forn react-redux will be used to create props from the reducer state